language: go
sudo: true
go:
 - 1.10.x

# Only build master branch.  This avoids double builds when pushing pr branches.
branches:
  only:
    - master

before_install:
  # We need tesseract 4 to get reliable recognition.
  - sudo add-apt-repository -y ppa:alex-p/tesseract-ocr
  - sudo apt-get update
  - sudo apt-get install -y tesseract-ocr-dev tesseract-ocr-eng libleptonica-dev
  - go get github.com/mattn/goveralls
  # If we don't export TZ, times stored in storm come back with a nil Localtion.
  - export TZ=America/Los_Angeles
script:
  - go run scripts/cover/cover.go

after_success:
  - goveralls -service=travis-ci -coverprofile=coverage.out
