language: go
sudo: true
go:
 - 1.10.x
before_install:
  - sudo add-apt-repository -y ppa:alex-p/tesseract-ocr
  - sudo apt-get update
  - sudo apt-get install -y tesseract-ocr-dev tesseract-ocr-eng libleptonica-dev
  - go get github.com/mattn/goveralls
  - export TZ=America/Los_Angeles
script:
 - $HOME/gopath/bin/goveralls -service=travis-ci
